### PR TITLE
Allow external comments to be found

### PR DESCRIPTION
**Pull request by cakeinpanic**
#1

I've I've created pullrequest and edited test to show what i've meant

### CODE REVIEW

**Comment by cakeinpanic** [comment]
Hello!
What do you think about meting this PR? I'm waiting for it to use in my project

**Comment by cakeinpanic** [comment]
If you don't like HTMLs to be wrapped all the time, let's make it an option

**Comment by Aratramba** [comment]
sorry, don't have time to look at this today. I will check it out tomorrow.

**Comment by Aratramba** [comment]
so what I see in this PR is this:

**1. change gitignore**
Not ok: don't think this is relevant

**2. change readme**
ok

**3. rename test file 'snippet' to 'external comment'**
Not ok: It's not about the external comment. It's about the multiple root nodes, so snippet isn't the most adequate name, but external comment doesn't describe its contents either.

**4. remove test**
Not ok: I hardly think removing a test case is the way to go to prove your case.

**5. remove check for multiple roots**
Ok: This is what it's about of course, and this seems to work. What I do not understand is why the old code works for all test cases on my computer, and doesn't on yours. Not that it really matters though, since all tests are green with the updated code.

I've manually changed this and updated npm with version 0.3.0.

**Comment by cakeinpanic** [comment]
You have published wrong git tag: 0.0.3 instead of  0.3.0

**Comment by cakeinpanic** [comment]
1.  Don't you think there is separate PR needed to add `.idea` to `.gitignore`?)
2. I think it is the same case: multiple root nodes, external comments, as soon as I suggest to wrap everything in div anyway
3. Remove fixture - remove its test. New `external-comment.html` was duplicating `non-html-root.html` in all cases

By the way for case

```
<html></html>
<!-- comment -->
```

tests don't pass too. 
So i suggest to wrap everything in `div` unconditionally

**Comment by Aratramba** [comment]
> You have published wrong git tag: 0.0.3 instead of 0.3.0

not sure what you mean, since I hadn't yet published a git tag but have only published it to npm. I have now: https://github.com/Aratramba/html-comments/releases/tag/0.3.0

> Don't you think there is separate PR needed to add .idea to .gitignore?)

I'm not sure what the use of a .idea file is. Is that an editor thing? Have added it to gitignore in 0.4.0.

> I think it is the same case: multiple root nodes, external comments, as soon as I suggest to wrap everything in div anyway

That's true, good point, still think it can't hurt to test all those cases separately. I suppose I just like to have lots of scenarios handy in case something needs to be rewritten.

> By the way for case
> <html></html>
> 
> 
> 
> tests don't pass too. 
> So i suggest to wrap everything in div unconditionally

Good one, you convinced me with this. I guess I like tidy html, what`<div><html></html></div>` clearly isn't – but cheerio doesn't seem to care at all. So I've removed that condition.

https://www.npmjs.com/package/html-comments
https://github.com/Aratramba/html-comments/releases/tag/0.4.0

Also reminds me why the second check for multiple root nodes was there in the first place. That was for this scenario where an html node was found but it wasn't the only root node.

```
<html></html>
<div></div>
<!-- comment -->
```

**Pull request closed without merging**
